import Config

config :mana_chess_online, :secure_session_cookie, true

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix assets.deploy` task,
# which you should run after static files are built and
# before starting your production server.
config :mana_chess_online, ManaChessOnlineWeb.Endpoint,
  cache_static_manifest: "priv/static/cache_manifest.json"

# Force using SSL in production. This also sets the "strict-security-transport" header,
# known as HSTS. If you have a health check endpoint, you may want to exclude it below.
# Note `:force_ssl` is required to be set at compile-time.
config :mana_chess_online, ManaChessOnlineWeb.Endpoint,
  force_ssl: [
    rewrite_on: [:x_forwarded_proto],
    exclude: [
      paths: ["/health"],
      hosts: ["localhost", "127.0.0.1"]
    ]
  ]

# Do not print debug messages in production
config :logger, level: :info

config :logger, :default_formatter,
  format: {ManaChessOnline.Operations.LogFormatter, :format},
  metadata: [
    :code,
    :component,
    :count,
    :duration_ms,
    :event,
    :event_at,
    :event_type,
    :method,
    :reason_class,
    :request_id,
    :route,
    :source,
    :status,
    :suppressed_since_last
  ],
  utc_log: true

# Runtime production configuration, including reading
# of environment variables, is done on config/runtime.exs.
